<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/><meta name="author" content="phi.friday@gmail.com, phi"/><meta name="robots" content="index,follow,noarchive"/><meta name="google-site-verification" content="lW107Dj5ageygd67UUzTm-kGls5d-THy9jJQZqLoauw"/><title>phi.log - sqlmodel 라이브러리 사용시 주의사항 - validation</title><link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet"/><meta name="next-head-count" content="7"/><link rel="preload" href="/_next/static/css/e61452b80f7f8356.css" as="style"/><link rel="stylesheet" href="/_next/static/css/e61452b80f7f8356.css" data-n-g=""/><link rel="preload" href="/_next/static/css/1f4d813b299120ae.css" as="style"/><link rel="stylesheet" href="/_next/static/css/1f4d813b299120ae.css" data-n-p=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-5752944655d749a0.js" defer=""></script><script src="/_next/static/chunks/framework-bb5c596eafb42b22.js" defer=""></script><script src="/_next/static/chunks/main-5dc3bdee87ff18dd.js" defer=""></script><script src="/_next/static/chunks/pages/_app-f6271bdec05edb1f.js" defer=""></script><script src="/_next/static/chunks/996-f3cf67c2e3ac5e06.js" defer=""></script><script src="/_next/static/chunks/756-1349105dbea71525.js" defer=""></script><script src="/_next/static/chunks/3-4b8664ceef873544.js" defer=""></script><script src="/_next/static/chunks/224-ddba219ecdd5c904.js" defer=""></script><script src="/_next/static/chunks/pages/posts/%5B...name%5D-98f81935dc747879.js" defer=""></script><script src="/_next/static/MQ_lMVQgBI0RkmUA6wvVT/_buildManifest.js" defer=""></script><script src="/_next/static/MQ_lMVQgBI0RkmUA6wvVT/_ssgManifest.js" defer=""></script><script src="/_next/static/MQ_lMVQgBI0RkmUA6wvVT/_middlewareManifest.js" defer=""></script></head><body><div id="__next" data-reactroot=""><style>
      #nprogress {
        pointer-events: none;
      }
      #nprogress .bar {
        background: #29D;
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 3px;
      }
      #nprogress .peg {
        display: block;
        position: absolute;
        right: 0px;
        width: 100px;
        height: 100%;
        box-shadow: 0 0 10px #29D, 0 0 5px #29D;
        opacity: 1;
        -webkit-transform: rotate(3deg) translate(0px, -4px);
        -ms-transform: rotate(3deg) translate(0px, -4px);
        transform: rotate(3deg) translate(0px, -4px);
      }
      #nprogress .spinner {
        display: block;
        position: fixed;
        z-index: 1031;
        top: 15px;
        right: 15px;
      }
      #nprogress .spinner-icon {
        width: 18px;
        height: 18px;
        box-sizing: border-box;
        border: solid 2px transparent;
        border-top-color: #29D;
        border-left-color: #29D;
        border-radius: 50%;
        -webkit-animation: nprogresss-spinner 400ms linear infinite;
        animation: nprogress-spinner 400ms linear infinite;
      }
      .nprogress-custom-parent {
        overflow: hidden;
        position: relative;
      }
      .nprogress-custom-parent #nprogress .spinner,
      .nprogress-custom-parent #nprogress .bar {
        position: absolute;
      }
      @-webkit-keyframes nprogress-spinner {
        0% {
          -webkit-transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
        }
      }
      @keyframes nprogress-spinner {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }
    </style><div class="container" style="max-width:900px;min-width:400px"><div class="container default_app"><header><div class="container"><nav class="navbar-light fixed-top navbar navbar-expand-sm bg-light" role="navigation"><div class="container" style="max-width:900px"><div class="container-fluid"><ul class="navbar-nav w-100"><li class="nav-item"><a data-test="nav-link" class="nav-link" href="/"><div class="text-nowrap nav_text__4OEN1"><i class="fa fa-home"></i> Home</div></a></li><li class="nav-item"><a data-test="nav-link" class="nav-link" href="/posts/@tag"><div class="text-nowrap nav_text__4OEN1"><i class="fa fa-hashtag"></i> Post</div></a></li><li class="nav-item"><a data-test="nav-link" class="nav-link" href="/posts/@page"><div class="text-nowrap nav_text__4OEN1"><i class="fa fa-blog"></i> Page</div></a></li><div class="container d-flex justify-content-end align-self-center"><div class="row"><div class="col"><form class="input-group w-auto" method="get" action="https://www.google.com/search" target="_blank" style="min-width:230px"><input type="hidden" name="sitesearch" value="phi-friday.github.io"/><input type="search" class="form-control" placeholder="Search in Google" aria-label="Search" name="q" maxLength="255"/><button class="ripple ripple-surface btn btn-outline-primary" role="button"><i class="fa fa-search"></i></button></form></div></div></div></ul></div></div></nav></div></header><main><div class="container"><article><div class="row"><div class="display-6 mb-3">sqlmodel 라이브러리 사용시 주의사항 - validation</div><h6 class="mb-0 text-muted text-end"><time dateTime="2022-05-02T18:53:19.408+09:00">작성일: 2022년 5월 2일 18시 53분 19초</time></h6><h6 class="mt-0 text-muted text-end"><time dateTime="2022-08-13T00:12:20.000+09:00">수정일: 2022년 8월 13일 24시 12분 20초</time></h6><div class="d-flex justify-content-end"><div><span><span class="badge bg-info mx-1">#python<!-- --> </span></span><span><span class="badge bg-info mx-1">#sqlmodel<!-- --> </span></span></div></div></div><div class="row"><div class="mt-3 mb-5 border-top"></div></div><div class="row"><div><div class="toolbar"><div></div></div><div class="markdown-body"><nav class="toc"><ol class="toc-level toc-level-1"></ol></nav><p><code>sqlmodel</code>은 <code>fastapi</code>의 개발자 <code>tiangolo</code>의 주도 하에 개발이 진행중인 <code>sql</code>관련 라이브러리입니다. <code>pydantic</code>의 모델과 <code>sqlalchemy</code>의 테이블을 한번의 정의로 같이 쓸 수 있다는 장점이 있어서, 다소 불안정한 부분이 있더라도 종종 쓰고 있습니다.</p>
<p>그런데 최근 아주 무서운 일을 확인했습니다.. <code>sqlmodel</code>로 정의한 모델에 <code>table=True</code>옵션을 주면 <code>pydantic</code>에서 자랑하는 검증 과정이 전혀 작동하지 않는다는 사실을..</p>
<p><code>from_orm</code>, <code>parse_obj</code> 이 두 메소드 모두 정상적으로 작동하지 않으니, <code>validate</code> 메소드를 이용해서 레코드를 생성하면 정상적으로 사용할 수 있는 것 같습니다.</p></div></div></div><div class="row"><div class="mt-5 mb-3 border-bottom"></div></div><div class="row"><span class="d-flex justify-content-between"><span><h6 class=""><i class="fa fa-angle-left mx-2"></i>fastapi 튜토리얼 -4- pytest...</h6></span><span><h6 class="">fastapi 튜토리얼 -5- TDD...<i class="fa fa-angle-right mx-2"></i></h6></span></span><div class="mt-3"><div><section style="width:100%"></section></div></div></div></article></div></main><footer class="text-center text-muted"></footer></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"post":{"name":"sqlmodel 라이브러리 사용시 주의사항 - validation","content":"`sqlmodel`은 `fastapi`의 개발자 `tiangolo`의 주도 하에 개발이 진행중인 `sql`관련 라이브러리입니다. `pydantic`의 모델과 `sqlalchemy`의 테이블을 한번의 정의로 같이 쓸 수 있다는 장점이 있어서, 다소 불안정한 부분이 있더라도 종종 쓰고 있습니다.\n\n그런데 최근 아주 무서운 일을 확인했습니다.. `sqlmodel`로 정의한 모델에 `table=True`옵션을 주면 `pydantic`에서 자랑하는 검증 과정이 전혀 작동하지 않는다는 사실을..\n\n`from_orm`, `parse_obj` 이 두 메소드 모두 정상적으로 작동하지 않으니, `validate` 메소드를 이용해서 레코드를 생성하면 정상적으로 사용할 수 있는 것 같습니다.\n","mtime":"2022-08-13T00:12:20.000+09:00","href":"velog/sqlmodel 라이브러리 사용시 주의사항 - validation","data":{"title":"sqlmodel 라이브러리 사용시 주의사항 - validation","date":"2022-05-02T18:53:19.408+09:00","tags":["python","sqlmodel","@all"],"page":null,"summary":"sqlmodel에서 모델에 table=True 옵션을 주면 from_orm, parse_obj에서 validation 과정을 진행하지 않는다."}},"prev_post":{"name":"fastapi 튜토리얼 -4- pytest 적용 및 실행","content":"\n**`fastapi`** 사용법을 다시 공부할겸, 참고할만한 좋은 [예제](https://www.jeffastor.com/blog/populating-cleaning-jobs-with-user-offers-in-fastapi)가 있어서 이 시리즈를 약간의 변경을 주고 따라가보려 한다.\n지난번처럼 어쩌다 그만둘 수도 있긴 하지만...\n\n---\n\n## `pytest`를 사용한 테스트 코드 작성 및 실행\n\n테스트 코드를 작성하는게 도움이 된다 아니다로 많이 싸우지만, 적어도 **jeffastor** 자신은 이 과정 자체를 즐기고 있다고 밝히며, **`pytest`** 를 적용하는데 한 챕터를 할애한다.\n\n### 패키지 설치\n\n우선 테스트 코드 종속성 패키지부터 설치한다.\n\n```bash\n❯ poetry add --dev pytest pytest-asyncio httpx asgi-lifespan\n```\n\n\u003e **`pytest-asyncio`** 는 비동기로 작성된 api를 테스트하는데 사용하고, **asgi-lifespan`** 은 앱을 실행하지 않고 테스트하기 위해 사용한다.\n\n그리고 이제 **`pytest`** 가 **`docker`** 에서 실행될 수 있게, 개발용 종속성 패키지도 **`docker`** 이미지를 빌드과정에 추가한다.\n\n```bash\n❯ poetry export -f requirements.txt --output backend/requirements.txt --without-hashes --dev\n❯ docker-compose build\n```\n\n### `pytest` 설정 파일 작성\n\n이제 기본적인 테스트 코드를 작성한다.\n\n```bash\n❯ touch backend/tests/__init__.py backend/tests/conftest.py backend/tests/test_cleanings.py\n```\n\n```python\n# backend/tests/conftest.py\nimport os\nimport warnings\nfrom typing import AsyncIterator\n\nimport alembic\nimport pytest\nfrom alembic.config import Config\nfrom asgi_lifespan import LifespanManager\nfrom fastapi import FastAPI\nfrom httpx import AsyncClient\nfrom sqlalchemy.ext.asyncio.engine import AsyncEngine\nfrom sqlmodel.ext.asyncio.session import AsyncSession\n\n\n# Apply migrations at beginning and end of testing session\n@pytest.fixture(scope=\"session\")\ndef apply_migrations():\n    warnings.filterwarnings(\"ignore\", category=DeprecationWarning)\n    os.environ[\"TESTING\"] = \"1\"\n    config = Config(\"alembic.ini\")\n\n    alembic.command.upgrade(config, \"head\")  # type: ignore\n    yield\n    alembic.command.downgrade(config, \"base\")  # type: ignore\n\n\n# Create a new application for testing\n@pytest.fixture\ndef app(apply_migrations: None) -\u003e FastAPI:\n    from app.api.server import get_application\n\n    return get_application()\n\n\n# Grab a reference to our database when needed\n@pytest.fixture\ndef engine(app: FastAPI) -\u003e AsyncEngine:\n    return app.state._db\n\n\n@pytest.fixture\nasync def session(engine: AsyncEngine) -\u003e AsyncSession:\n    session = AsyncSession(engine, autoflush=False, autocommit=False)\n    try:\n        return session\n    finally:\n        await session.close()\n\n\n# Make requests in our tests\n@pytest.fixture\nasync def client(app: FastAPI) -\u003e AsyncIterator[AsyncClient]:\n    async with LifespanManager(app):\n        async with AsyncClient(\n            app=app,\n            base_url=\"http://testserver\",\n            headers={\"Content-Type\": \"application/json\"},\n        ) as client:\n            yield client\n\n```\n\n[원문](https://www.jeffastor.com/blog/testing-fastapi-endpoints-with-docker-and-pytest)에 설명이 꽤 있으니 읽어보면 좋을듯.\n\n### 테스트 데이터베이스 엔진 및 마이그레이션 설정\n\n추가로 테스트 환경에서 정상적으로 작동하도록, 기존에 작성한 모듈을 수정한다.\n\n```python\n# backend/app/db/engine.py\nfrom os import getenv\n\nfrom sqlalchemy.engine.url import URL\nfrom sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine\nfrom sqlalchemy.pool import QueuePool\n\nfrom ..core.config import DATABASE_URL\n\n\ndef is_test() -\u003e bool:\n    return (env_val := getenv(\"TESTING\", None)) is not None and bool(env_val)\n\n\ndef get_test_url(url: URL) -\u003e URL:\n    if url.database is None:\n        raise ValueError(\"database name is None\")\n\n    return url.set(database=f\"{url.database}_test\")\n\n\ndef get_test_engine(engine: AsyncEngine) -\u003e AsyncEngine:\n    if not is_test():\n        return engine\n    return create_engine_from_url(get_test_url(engine.url))\n\n\ndef create_engine_from_url(url: str | URL, **kwargs: Any) -\u003e AsyncEngine:\n    return create_async_engine(\n        url, pool_size=10, poolclass=QueuePool, pool_pre_ping=True, **kwargs\n    )\n\n\nengine = create_engine_from_url(DATABASE_URL)\n```\n\n```python\n# backend/app/db/tasks.py\n(...)\n\nfrom .engine import engine, get_test_engine\n\n(...)\n\nasync def connect_to_db(app: FastAPI) -\u003e None:\n    _engine = get_test_engine(engine)\n\n    try:\n        async with _engine.connect():\n            logger.info(\n                f\"connected db: {_engine.url.render_as_string(hide_password=True)}\"\n            )\n        app.state._db = _engine\n    except Exception as e:\n        logger.warning(\"--- DB CONNECTION ERROR ---\")\n        logger.warning(e)\n        logger.warning(\"--- DB CONNECTION ERROR ---\")\n\n(...)\n```\n\n```python\n# backend/app/db/migrations/env.py\nimport asyncio\nimport logging\nimport pathlib\nimport sys\nfrom logging.config import fileConfig\nfrom typing import cast\n\nfrom alembic import context\nfrom sqlalchemy import engine_from_config, pool\nfrom sqlalchemy.exc import InvalidRequestError\nfrom sqlalchemy.ext.asyncio import AsyncEngine\nfrom sqlalchemy.future.engine import Engine\n\nsys.path.append(str(pathlib.Path(__file__).resolve().parents[3]))\nfrom app.db.engine import engine, get_test_url, is_test\n\n# this is the Alembic Config object, which provides\n# access to the values within the .ini file in use.\nconfig = context.config\n\n# Interpret the config file for Python logging.\n# This line sets up loggers basically.\nif config.config_file_name is not None:\n    fileConfig(config.config_file_name)\nlogger = logging.getLogger(\"alembic.env\")\n\n# add your model's MetaData object here\n# for 'autogenerate' support\n# from myapp import mymodel\n# target_metadata = mymodel.Base.metadata\ntarget_metadata = None\n\n# other values from the config, defined by the needs of env.py,\n# can be acquired:\n# my_important_option = config.get_main_option(\"my_important_option\")\n# ... etc.\n\n\ndef run_migrations_offline():\n    \"\"\"Run migrations in 'offline' mode.\n\n    This configures the context with just a URL\n    and not an Engine, though an Engine is acceptable\n    here as well.  By skipping the Engine creation\n    we don't even need a DBAPI to be available.\n\n    Calls to context.execute() here emit the given string to the\n    script output.\n\n    \"\"\"\n    if is_test():\n        raise InvalidRequestError(\n            \"Running testing migrations offline currently not permitted.\"\n        )\n\n    # url = config.get_main_option(\"sqlalchemy.url\")\n    context.configure(\n        # url=url,\n        url=engine.url.render_as_string(hide_password=False),\n        target_metadata=target_metadata,\n        literal_binds=True,\n        dialect_opts={\"paramstyle\": \"named\"},\n    )\n\n    with context.begin_transaction():\n        context.run_migrations()\n\n\ndef do_run_migrations(connection):\n    context.configure(connection=connection, target_metadata=target_metadata)\n\n    with context.begin_transaction():\n        context.run_migrations()\n\n\nasync def run_migrations_online():\n    \"\"\"Run migrations in 'online' mode.\n\n    In this scenario we need to create an Engine\n    and associate a connection with the context.\n\n    \"\"\"\n    url = engine.url\n    if is_test():\n        from sqlalchemy import text\n\n        url = get_test_url(url)\n        async with engine.connect() as conn:\n            conn = await conn.execution_options(isolation_level=\"AUTOCOMMIT\")\n            await conn.execute(text(f\"drop database if exists {url.database}\"))\n            await conn.execute(text(f\"create database {url.database}\"))\n\n    config.set_main_option(\"sqlalchemy.url\", url.render_as_string(hide_password=False))\n    connectable = AsyncEngine(\n        cast(\n            Engine,\n            engine_from_config(\n                config.get_section(config.config_ini_section),\n                prefix=\"sqlalchemy.\",\n                poolclass=pool.NullPool,\n                future=True,\n            ),\n        )\n    )\n\n    async with connectable.connect() as connection:\n        await connection.run_sync(do_run_migrations)\n\n    await connectable.dispose()\n\n\nif context.is_offline_mode():\n    logger.info(\"Running migrations offline\")\n    run_migrations_offline()\nelse:\n    logger.info(\"Running migrations online\")\n    asyncio.run(run_migrations_online())\n```\n\n이제 `TESTING`이라는 환경변수 값이 정상적으로 입력되어 있다면 테스트 DB를 사용한다. 또한, 마이그레이션시 테스트 DB가 이미 생성되어 있다면, 해당 DB를 지우고 새로 생성한다.\n\n### 테스트 코드 작성\n\n이제 이전에 작성한 라우터를 테스트 하는 테스트 코드를 작성한다.\n\n```python\n# backend/tests/test_cleanings.py\nimport pytest\nfrom fastapi import FastAPI\nfrom httpx import AsyncClient\nfrom starlette.status import HTTP_404_NOT_FOUND, HTTP_422_UNPROCESSABLE_ENTITY\n\n\nclass TestCleaningsRoutes:\n    @pytest.mark.asyncio\n    async def test_routes_exist(self, app: FastAPI, client: AsyncClient) -\u003e None:\n        res = await client.post(app.url_path_for(\"cleanings:create-cleaning\"), json={})\n        assert res.status_code != HTTP_404_NOT_FOUND\n\n    @pytest.mark.asyncio\n    async def test_invalid_input_raises_error(\n        self, app: FastAPI, client: AsyncClient\n    ) -\u003e None:\n        res = await client.post(app.url_path_for(\"cleanings:create-cleaning\"), json={})\n        assert res.status_code != HTTP_422_UNPROCESSABLE_ENTITY\n```\n\n이 테스트 코드는 우선 이전 챕터에서 작성한 `cleanings:create-cleaning` api가 존재하는지, 그리고 정상적으로 작동하는지 확인한다.\n\n이전에 어떻게 사용되는지 몰랐던 `conftest.py`에서 `pytest.fixture`로 데코레이트된 함수 `app`, `client`가 여기서 사용된다. `TestCleaningsRoutes`의 각 메소드의 파라미터와 이름이 일치하는 함수를 호출하여, 리턴값을 파라미터로 사용한다.\n\n`TestCleaningsRoutes.test_invalid_input_raises_error`에서 `json` 파라미터로 빈 딕셔너리를 제공했기에, 이전에 작성한 모델인 `cleaning_create`의 필수 값인 `name`과 `price`이 없어서 에러가 발생할 것으로 예상된다.\n\n이제 실제로 테스트를 실행해본다.\n\n```bash\nroot@3190a4d68f18:/backend# pytest -v\n==================================================== test session starts =====================================================\nplatform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python\ncachedir: .pytest_cache\nrootdir: /backend\nplugins: anyio-3.5.0, asyncio-0.18.3\nasyncio: mode=legacy\ncollected 2 items\n\ntests/test_cleanings.py::TestCleaningsRoutes::test_routes_exist PASSED                                                 [ 50%]\ntests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error FAILED                                   [100%]\ntests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error ERROR                                    [100%]\n\n=========================================================== ERRORS ===========================================================\n__________________________ ERROR at teardown of TestCleaningsRoutes.test_invalid_input_raises_error __________________________\n\n    @pytest.fixture(scope=\"session\")\n    def apply_migrations():\n        warnings.filterwarnings(\"ignore\", category=DeprecationWarning)\n        os.environ[\"TESTING\"] = \"1\"\n        config = Config(\"alembic.ini\")\n\n        alembic.command.upgrade(config, \"head\")  # type: ignore\n        yield\n\u003e       alembic.command.downgrade(config, \"base\")  # type: ignore\n\ntests/conftest.py:24:\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n(...)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n\u003e   ???\nE   RuntimeError: Task \u003cTask pending name='Task-20' coro=\u003crun_migrations_online() running at /backend/./app/db/migrations/env.py:88\u003e cb=[_run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]\u003e got Future \u003cFuture pending cb=[Protocol._on_waiter_completed()]\u003e attached to a different loop\n\nasyncpg/protocol/protocol.pyx:338: RuntimeError\n-------------------------------------------------- Captured stderr teardown --------------------------------------------------\nINFO  [alembic.env] Running migrations online\n========================================================== FAILURES ==========================================================\n____________________________________ TestCleaningsRoutes.test_invalid_input_raises_error _____________________________________\n\nself = \u003ctests.test_cleanings.TestCleaningsRoutes object at 0x7fc9e092b610\u003e\napp = \u003cfastapi.applications.FastAPI object at 0x7fc9e0928eb0\u003e, client = \u003chttpx.AsyncClient object at 0x7fc9df873640\u003e\n\n    @pytest.mark.asyncio\n    async def test_invalid_input_raises_error(\n        self, app: FastAPI, client: AsyncClient\n    ) -\u003e None:\n        res = await client.post(app.url_path_for(\"cleanings:create-cleaning\"), json={})\n\u003e       assert res.status_code != HTTP_422_UNPROCESSABLE_ENTITY\nE       assert 422 != 422\nE        +  where 422 = \u003cResponse [422 Unprocessable Entity]\u003e.status_code\n\ntests/test_cleanings.py:18: AssertionError\n====================================================== warnings summary ======================================================\n../usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191\n  /usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.\n    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)\n\n../usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:230\n  /usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:230: DeprecationWarning: '@pytest.fixture' is applied to \u003cfixture client, file=/backend/tests/conftest.py, line=42\u003e in 'legacy' mode, please replace it with '@pytest_asyncio.fixture' as a preparation for switching to 'strict' mode (or use 'auto' mode to seamlessly handle all these fixtures as asyncio-driven).\n    warnings.warn(\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n================================================== short test summary info ===================================================\nFAILED tests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error - assert 422 != 422\nERROR tests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error - RuntimeError: Task \u003cTask pending name...\n====================================== 1 failed, 1 passed, 2 warnings, 1 error in 0.44s ======================================\nsys:1: SAWarning: The garbage collector is trying to clean up connection \u003cAdaptedConnection \u003casyncpg.connection.Connection object at 0x7fc9e082a6c0\u003e\u003e. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.\n```\n\n예상했던 첫번째와 달리, 두번째 에러가 당황스럽다. 확인해보니 비동기 엔진을 **`pytest`** 에서 사용할 때, 이벤트 루프 때문에 런타임 에러가 발생했다. **`pytest`** 에 익숙하지 않기에, 해결할 방법 또한 당장 알아내기가 어렵다. 급한대로 **`alembic`** 사용시 동기 엔진을 사용하기로 했다.\n\n```bash\n❯ poetry add --dev psycopg2-binary\n❯ poetry export -f requirements.txt --output backend/requirements.txt --without-hashes --dev\n❯ docker-compose build\n```\n\n```python\n# backend/app/db/engine.py\nfrom os import getenv\nfrom typing import Any, Literal, overload\n\nfrom sqlalchemy import create_engine\nfrom sqlalchemy.engine.url import URL\nfrom sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine\nfrom sqlalchemy.future.engine import Engine\nfrom sqlalchemy.pool import QueuePool\n\nfrom ..core.config import DATABASE_URL\n\n\ndef is_test() -\u003e bool:\n    return (env_val := getenv(\"TESTING\", None)) is not None and bool(env_val)\n\n\ndef get_test_url(url: URL) -\u003e URL:\n    if url.database is None:\n        raise ValueError(\"database name is None\")\n\n    return url.set(database=f\"{url.database}_test\")\n\n\ndef get_engine_kwargs(**kwargs: Any) -\u003e dict[str, Any]:\n    return {\n        \"pool_size\": 10,\n        \"poolclass\": QueuePool,\n        \"pool_pre_ping\": True,\n        \"future\": True,\n    } | kwargs\n\n\n@overload\ndef get_test_engine(engine: AsyncEngine) -\u003e AsyncEngine:\n    ...\n\n\n@overload\ndef get_test_engine(engine: AsyncEngine, is_sync: Literal[True] = ...) -\u003e Engine:\n    ...\n\n\n@overload\ndef get_test_engine(engine: AsyncEngine, is_sync: Literal[False] = ...) -\u003e AsyncEngine:\n    ...\n\n\n@overload\ndef get_test_engine(engine: AsyncEngine, is_sync: bool = ...) -\u003e AsyncEngine | Engine:\n    ...\n\n\ndef get_test_engine(engine: AsyncEngine, is_sync: bool = False) -\u003e AsyncEngine | Engine:\n    if is_test():\n        engine = create_engine_from_url(\n            get_test_url(engine.url), pool_pre_ping=pool_pre_ping\n        )\n\n    if is_sync:\n        return convert_async_to_sync(engine)\n    return engine\n\n\ndef convert_async_to_sync(engine: AsyncEngine, **kwargs: Any) -\u003e Engine:\n    return create_sync_engine_from_url(\n        engine.url.set(drivername=engine.url.drivername.split(\"+\")[0]), **kwargs\n    )\n\n\ndef create_sync_engine_from_url(url: str | URL, **kwargs: Any) -\u003e Engine:\n    return create_engine(url, **get_engine_kwargs(**kwargs))\n\n\ndef create_engine_from_url(url: str | URL, **kwargs: Any) -\u003e AsyncEngine:\n    return create_async_engine(url, **get_engine_kwargs(**kwargs))\n\n\nengine = create_engine_from_url(DATABASE_URL)\n```\n\n```python\n# backend/app/db/migrations/env.py\nimport logging\nimport pathlib\nimport sys\nfrom logging.config import fileConfig\n\nfrom alembic import context\nfrom sqlalchemy import engine_from_config, pool\nfrom sqlalchemy.exc import InvalidRequestError\n\nsys.path.append(str(pathlib.Path(__file__).resolve().parents[3]))\nfrom app.db.engine import engine, get_test_engine, is_test\n\n# this is the Alembic Config object, which provides\n# access to the values within the .ini file in use.\nconfig = context.config\n\n# Interpret the config file for Python logging.\n# This line sets up loggers basically.\nif config.config_file_name is not None:\n    fileConfig(config.config_file_name)\nlogger = logging.getLogger(\"alembic.env\")\n\n# add your model's MetaData object here\n# for 'autogenerate' support\n# from myapp import mymodel\n# target_metadata = mymodel.Base.metadata\ntarget_metadata = None\n\n# other values from the config, defined by the needs of env.py,\n# can be acquired:\n# my_important_option = config.get_main_option(\"my_important_option\")\n# ... etc.\n\n\ndef run_migrations_offline():\n    \"\"\"Run migrations in 'offline' mode.\n\n    This configures the context with just a URL\n    and not an Engine, though an Engine is acceptable\n    here as well.  By skipping the Engine creation\n    we don't even need a DBAPI to be available.\n\n    Calls to context.execute() here emit the given string to the\n    script output.\n\n    \"\"\"\n    if is_test():\n        raise InvalidRequestError(\n            \"Running testing migrations offline currently not permitted.\"\n        )\n\n    # url = config.get_main_option(\"sqlalchemy.url\")\n    context.configure(\n        # url=url,\n        url=engine.url.render_as_string(hide_password=False),\n        target_metadata=target_metadata,\n        literal_binds=True,\n        dialect_opts={\"paramstyle\": \"named\"},\n    )\n\n    with context.begin_transaction():\n        context.run_migrations()\n\n\ndef do_run_migrations(connection):\n    context.configure(connection=connection, target_metadata=target_metadata)\n\n    with context.begin_transaction():\n        context.run_migrations()\n\n\ndef run_migrations_online():\n    \"\"\"Run migrations in 'online' mode.\n\n    In this scenario we need to create an Engine\n    and associate a connection with the context.\n\n    \"\"\"\n    _engine = get_test_engine(engine, is_sync=True)\n    url = _engine.url\n\n    if is_test():\n        from sqlalchemy import text\n\n        with _engine.connect() as conn:\n            conn = conn.execution_options(isolation_level=\"AUTOCOMMIT\")\n            conn.execute(text(f\"drop database if exists {url.database}\"))\n            conn.execute(text(f\"create database {url.database}\"))\n\n    config.set_main_option(\"sqlalchemy.url\", url.render_as_string(hide_password=False))\n    connectable = engine_from_config(\n        config.get_section(config.config_ini_section),\n        prefix=\"sqlalchemy.\",\n        poolclass=pool.NullPool,\n        future=True,\n    )\n\n    with connectable.connect() as connection:\n        do_run_migrations(connection)\n\n    connectable.dispose()\n\n\nif context.is_offline_mode():\n    logger.info(\"Running migrations offline\")\n    run_migrations_offline()\nelse:\n    logger.info(\"Running migrations online\")\n    run_migrations_online()\n```\n\n이제 다시 **`pytest`** 를 실행해보면\n\n```bash\n(...)\n\n================================================== short test summary info ===================================================\nFAILED tests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error - assert 422 != 422\n================================================ 1 failed, 1 passed in 0.35s =================================================\n```\n\n정상적으로 2번째 메소드만 에러를 발생시킨다.\n이제 이전에 작성한 **POST** api에 대한 테스트 코드를 작성해보자.\n\n```python\n# backend/app/models/cleaning.py\n(...)\n\nclass cleaning_update(cleaning_base):\n    cleaning_type: cleaning_type_enum | None = None\n\n(...)\n```\n\n```python\n# backend/tests/test_cleanings.py\nimport orjson\nimport pytest\nfrom app.models.cleaning import cleaning_create\nfrom fastapi import FastAPI\nfrom httpx import AsyncClient\nfrom starlette.status import (\n    HTTP_201_CREATED,\n    HTTP_404_NOT_FOUND,\n    HTTP_422_UNPROCESSABLE_ENTITY,\n)\n\n# decorate all tests with @pytest.mark.asyncio\npytestmark = pytest.mark.asyncio\n\n\n@pytest.fixture\ndef new_cleaning():\n    return cleaning_create.parse_obj(\n        dict(\n            name=\"test cleaning\",\n            description=\"test description\",\n            price=0.00,\n            cleaning_type=\"spot_clean\",\n        )\n    )\n\n\nclass TestCleaningsRoutes:\n    async def test_routes_exist(self, app: FastAPI, client: AsyncClient) -\u003e None:\n        res = await client.post(app.url_path_for(\"cleanings:create-cleaning\"), json={})\n        assert res.status_code != HTTP_404_NOT_FOUND\n\n    async def test_invalid_input_raises_error(\n        self, app: FastAPI, client: AsyncClient\n    ) -\u003e None:\n        res = await client.post(app.url_path_for(\"cleanings:create-cleaning\"), json={})\n        assert res.status_code == HTTP_422_UNPROCESSABLE_ENTITY\n\n\nclass TestCreateCleaning:\n    async def test_valid_input_creates_cleaning(\n        self, app: FastAPI, client: AsyncClient, new_cleaning: cleaning_create\n    ) -\u003e None:\n        res = await client.post(\n            app.url_path_for(\"cleanings:create-cleaning\"),\n            json={\"new_cleaning\": orjson.loads(new_cleaning.json())},\n        )\n        assert res.status_code == HTTP_201_CREATED\n\n        created_cleaning = cleaning_create(**res.json())\n        assert created_cleaning == new_cleaning\n\n    @pytest.mark.parametrize(\n        \"invalid_payload, status_code\",\n        (\n            (None, 422),\n            ({}, 422),\n            ({\"name\": \"test_name\"}, 422),\n            ({\"price\": 10.00}, 422),\n            ({\"name\": \"test_name\", \"description\": \"test\"}, 422),\n        ),\n    )\n    async def test_invalid_input_raises_error(\n        self, app: FastAPI, client: AsyncClient, invalid_payload: dict, status_code: int\n    ) -\u003e None:\n        res = await client.post(\n            app.url_path_for(\"cleanings:create-cleaning\"),\n            json={\"new_cleaning\": invalid_payload},\n        )\n        assert res.status_code == status_code\n```\n\n`cleanings:create-cleaning` api가 의도한대로 데이터를 추가하고, 반환하는지 확인하는 코드가 추가됐다.\n\n또한, 에러를 발생하는 `body`의 형태와, 그러한 `body`에 대해 기대하는 `status_code`를 지정해서 확인한다.\n\n결과는 다음과 같이 정상적으로 나와야 한다.\n\n```bash\n==================================================== test session starts =====================================================\nplatform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python\ncachedir: .pytest_cache\nrootdir: /backend\nplugins: anyio-3.5.0, asyncio-0.18.3\nasyncio: mode=auto\ncollected 8 items\n\ntests/test_cleanings.py::TestCleaningsRoutes::test_routes_exist PASSED                                                 [ 12%]\ntests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error PASSED                                   [ 25%]\ntests/test_cleanings.py::TestCreateCleaning::test_valid_input_creates_cleaning PASSED                                  [ 37%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[None-422] PASSED                          [ 50%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload1-422] PASSED              [ 62%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload2-422] PASSED              [ 75%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload3-422] PASSED              [ 87%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload4-422] PASSED              [100%]\n\n===================================================== 8 passed in 0.54s ======================================================\n```\n\n## TDD 방법론에 따른 개발 연습\n\n이제 **`pytest`** 를 사용하는 방식에 대해 어느정도 감이 잡히는 느낌이다.\n**jeffastor**는 이러한 테스트 코드를 이용해서, **TDD**(테스트 주도 개발)을 권장하는 것 같다.\n**TDD**는 다음의 3단계 프로세스를 따른다.\n\n\u003e 1. 실패를 확인할 수 있는 테스트 코드를 작성한다.\n\u003e 2. 테스트 코드를 통과할 수 있도록 코드를 작성한다.\n\u003e 3. 자신이 만족할 수준으로 코드를 수정, 테스트, 리팩토링, 모듈화 등을 실시한다.\n\n### `GET` `api` 생성\n\n위 프로세스를 따라서 **GET** api를 생성해보자.\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nfrom app.models.cleaning import cleaning_create, cleanings\nfrom starlette.status import (\n    HTTP_200_OK,\n    HTTP_201_CREATED,\n    HTTP_404_NOT_FOUND,\n    HTTP_422_UNPROCESSABLE_ENTITY,\n)\n\n(...)\n\nclass TestGetCleaning:\n    async def test_get_cleaning_by_id(self, app: FastAPI, client: AsyncClient) -\u003e None:\n        res = await client.get(app.url_path_for(\"cleanings:get-cleaning-by-id\", id=\"1\"))\n        assert res.status_code == HTTP_200_OK\n        cleaning = cleanings(**res.json())\n        assert cleaning.id == 1\n```\n\n작성한 테스트 코드의 `TestGetCleaning.test_get_cleaning_by_id` 메소드를 통과할 수 있도록, **GET** api를 작성해보자.\n\n```python\n# backend/app/api/routes/cleanings.py\nfrom fastapi import APIRouter, Body, Depends, HTTPException, Path\nfrom starlette.status import HTTP_201_CREATED, HTTP_404_NOT_FOUND\n\n(...)\n\n@router.get(\n    \"/{id}\", response_model=cleaning_public, name=\"cleanings:get-cleaning-by-id\"\n)\nasync def get_cleaning_by_id(\n    id: int = Path(..., ge=1),\n    session: AsyncSession = Depends(get_session),\n) -\u003e cleanings:\n    if (cleaning := await session.get(cleanings, id)) is None:\n        raise HTTPException(\n            status_code=HTTP_404_NOT_FOUND, detail=\"No cleaning found with that id.\"\n        )\n    return cleaning\n```\n\n확인해본 결과, 모두 잘 작동한다.\n하지만 테스트 코드에 문제가 있다. `id=1`로 하드코딩된 상태이기 때문. 따라서 하드코딩을 제거하기 위한 새로운 `fixture`를 생성할 필요가 있다.\n\n```python\n# backend/tests/test_cleanings.py\n\n(...)\n\nfrom sqlmodel.ext.asyncio.session import AsyncSession\n\n(...)\n\n@pytest.fixture\nasync def test_cleaning(session: AsyncSession) -\u003e cleanings:\n    new_cleaning_create = cleaning_create.parse_obj(\n        dict(\n            name=\"fake cleaning name\",\n            description=\"fake cleaning description\",\n            price=9.99,\n            cleaning_type=\"spot_clean\",\n        )\n    )\n    new_cleaning = cleanings.from_orm(new_cleaning_create)\n    session.add(new_cleaning)\n    await session.commit()\n    await session.refresh(new_cleaning)\n\n    return new_cleaning\n\n\nclass TestGetCleaning:\n    async def test_get_cleaning_by_id(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        print(test_cleaning)\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(test_cleaning.id))\n        )\n        assert res.status_code == HTTP_200_OK\n        cleaning = cleanings.parse_obj(res.json())\n        assert cleaning == test_cleaning\n```\n\n`refresh` 메소드를 사용하여 정확한 id를 가지고 비교를 해서 에러가 없을거라 생각했는데,\n\n```bash\n================================================== short test summary info ===================================================\nERROR tests/test_cleanings.py::TestGetCleaning::test_get_cleaning_by_id - sqlalchemy.exc.OperationalError: (psycopg2.errors...\n================================================= 9 passed, 1 error in 5.74s =================================================\nsys:1: SAWarning: The garbage collector is trying to clean up connection \u003cAdaptedConnection \u003casyncpg.connection.Connection object at 0x7fabadaffbc0\u003e\u003e. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.\n```\n\n**`pytest`** 에서 `fixture`를 생성할 때 연결한 `session`을 제대로 정리하지 않아서 에러가 발생했다. **`pytest`** 에서는 `NullPool`을 사용하고, **`pytest`** 에서 `session` 객체를 `fixture`로 사용하지 않도록 하자.\n\n```python\nfrom sqlalchemy.pool import AsyncAdaptedQueuePool, NullPool, QueuePool\n\n(...)\n\ndef get_engine_kwargs(\n    is_sync: bool, is_test: bool = False, **kwargs: Any\n) -\u003e dict[str, Any]:\n    params: dict[str, Any] = {\"pool_pre_ping\": True, \"future\": True}\n\n    if is_test:\n        params[\"poolclass\"] = NullPool\n    else:\n        params[\"pool_size\"] = 10\n        params[\"poolclass\"] = QueuePool\n\n    return params | kwargs\n\n\n(...)\n\ndef get_test_engine(engine: AsyncEngine, is_sync: bool = False) -\u003e AsyncEngine | Engine:\n    if _is_test := is_test():\n        engine = create_engine_from_url(get_test_url(engine.url), is_test=_is_test)\n\n    if is_sync:\n        return convert_async_to_sync(engine, is_test=_is_test)\n    return engine\n\n(...)\n```\n\n```python\n# backend/tests/conftest.py\nimport os\nimport warnings\nfrom typing import AsyncIterator\n\nimport alembic\nimport pytest\nfrom alembic.config import Config\nfrom asgi_lifespan import LifespanManager\nfrom fastapi import FastAPI\nfrom httpx import AsyncClient\nfrom sqlalchemy.ext.asyncio.engine import AsyncEngine\n\n\n# Apply migrations at beginning and end of testing session\n@pytest.fixture(scope=\"session\")\ndef apply_migrations():\n    warnings.filterwarnings(\"ignore\", category=DeprecationWarning)\n    os.environ[\"TESTING\"] = \"1\"\n    config = Config(\"alembic.ini\")\n\n    alembic.command.upgrade(config, \"head\")  # type: ignore\n    yield\n    alembic.command.downgrade(config, \"base\")  # type: ignore\n\n\n# Create a new application for testing\n@pytest.fixture\ndef app(apply_migrations: None) -\u003e FastAPI:\n    from app.api.server import get_application\n\n    return get_application()\n\n\n# Grab a reference to our database when needed\n@pytest.fixture\ndef engine(app: FastAPI) -\u003e AsyncEngine:\n    return app.state._db\n\n\n# Make requests in our tests\n@pytest.fixture\nasync def client(app: FastAPI) -\u003e AsyncIterator[AsyncClient]:\n    async with LifespanManager(app):\n        async with AsyncClient(\n            app=app,\n            base_url=\"http://testserver\",\n            headers={\"Content-Type\": \"application/json\"},\n        ) as client:\n            yield client\n```\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nfrom sqlalchemy.ext.asyncio import AsyncEngine\nfrom sqlmodel.ext.asyncio.session import AsyncSession\n\n(...)\n\n@pytest.fixture\nasync def test_cleaning(engine: AsyncEngine) -\u003e cleanings:\n    new_cleaning_create = cleaning_create.parse_obj(\n        dict(\n            name=\"fake cleaning name\",\n            description=\"fake cleaning description\",\n            price=9.99,\n            cleaning_type=\"spot_clean\",\n        )\n    )\n    new_cleaning = cleanings.from_orm(new_cleaning_create)\n    async with AsyncSession(engine, autocommit=False) as session:\n        session.add(new_cleaning)\n        await session.commit()\n        await session.refresh(new_cleaning)\n\n    return new_cleaning\n\n(...)\n```\n\n다시 **`pytest`** 를 실행했을 때, 정상적으로 잘 되는 것을 확인했다.\n\n### `GET` `api`에 유효하지 않은 값에 대한 테스트 코드\n\n이어서, 유효하지 않은 값에 대한 테스트 코드를 추가한다.\n원 예제는 `id=-1`에 대해 404 에러 코드를 반환하지만, 이전에 **GET** api를 정의할 때 `id: int = Path(..., ge=1)` 으로 정의했기에 422에러가 반환된다. 따라서 그 부분만 수정했다.\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nclass TestGetCleaning:\n    async def test_get_cleaning_by_id(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        print(test_cleaning)\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(test_cleaning.id))\n        )\n        assert res.status_code == HTTP_200_OK\n        cleaning = cleanings.parse_obj(res.json())\n        assert cleaning == test_cleaning\n\n    @pytest.mark.parametrize(\n        \"id, status_code\",\n        (\n            (500, 404),\n            (-1, 422),\n            (None, 422),\n        ),\n    )\n    async def test_wrong_id_returns_error(\n        self, app: FastAPI, client: AsyncClient, id: int, status_code: int\n    ) -\u003e None:\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(id))\n        )\n        assert res.status_code == status_code\n```\n\n테스트시, 별 문제 없이 통과한다.\n\n```bash\nroot@5984264d864d:/backend# pytest -v --asyncio-mode=auto\n==================================================== test session starts =====================================================\nplatform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python\ncachedir: .pytest_cache\nrootdir: /backend\nplugins: anyio-3.5.0, asyncio-0.18.3\nasyncio: mode=auto\ncollected 12 items\n\ntests/test_cleanings.py::TestCleaningsRoutes::test_routes_exist PASSED                                                 [  8%]\ntests/test_cleanings.py::TestCleaningsRoutes::test_invalid_input_raises_error PASSED                                   [ 16%]\ntests/test_cleanings.py::TestCreateCleaning::test_valid_input_creates_cleaning PASSED                                  [ 25%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[None-422] PASSED                          [ 33%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload1-422] PASSED              [ 41%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload2-422] PASSED              [ 50%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload3-422] PASSED              [ 58%]\ntests/test_cleanings.py::TestCreateCleaning::test_invalid_input_raises_error[invalid_payload4-422] PASSED              [ 66%]\ntests/test_cleanings.py::TestGetCleaning::test_get_cleaning_by_id PASSED                                               [ 75%]\ntests/test_cleanings.py::TestGetCleaning::test_wrong_id_returns_error[500-404] PASSED                                  [ 83%]\ntests/test_cleanings.py::TestGetCleaning::test_wrong_id_returns_error[-1-422] PASSED                                   [ 91%]\ntests/test_cleanings.py::TestGetCleaning::test_wrong_id_returns_error[None-422] PASSED                                 [100%]\n\n===================================================== 12 passed in 0.86s =====================================================\n```\n\n다음 챕터는 CRUD api를 잘 생성하기 위한 작업으로 보인다.\n","mtime":"2022-08-13T00:12:20.000+09:00","href":"velog/fastapi 튜토리얼 -4- pytest 적용 및 실행","data":{"title":"fastapi 튜토리얼 -4- pytest 적용 및 실행","date":"2022-04-30T02:43:31.082+09:00","tags":["fastapi","tdd","pytest","python","@all"],"page":"fastapi 튜토리얼","summary":"fastapi 사용법을 다시 공부할겸, 참고할만한 좋은 예제가 있어서 이 시리즈를 약간의 변경을 주고 따라가보려 한다."}},"next_post":{"name":"fastapi 튜토리얼 -5- TDD 방법론으로 RESTful API 생성","content":"\n**`fastapi`** 사용법을 다시 공부할겸, 참고할만한 좋은 [예제](https://www.jeffastor.com/blog/populating-cleaning-jobs-with-user-offers-in-fastapi)가 있어서 이 시리즈를 약간의 변경을 주고 따라가보려 한다.\n지난번처럼 어쩌다 그만둘 수도 있긴 하지만...\n\n---\n\n아래 문제로 인해 해당 챕터를 진행하면서 이전 챕터의 글을 포함해서 수정하다 보니 제대로 수정이 된건지 아닌지 확인하기가 어렵다..\n어쩌면 [이곳](https://github.com/phi-friday/jeffastor_tutor)에서 코드를 확인하는게 도움이 될 수 있다.\n\n특히 이 챕터의 테스트 코드에 적용된 `Decimal`이나 `f-string`도 원래는 **TDD** 과정 중에서 적용한 것이지만, 이미 글 쓰는 흐름이 다 꼬여서 생략했다.\n\n---\n\n## `SQLModel`의 **validataion** 관련 해결\n\n[링크](https://velog.io/@phi0friday/sqlmodel-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%82%AC%EC%9A%A9%EC%8B%9C-%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD-validation)와 같은 이유로 인해, **`sqlmodel`** 로 생성한 모델에 대한 전반적인 수정이 필요하므로, 아래와 같이 수정을 진행했다.\n\n```python\n# backend/app/models/core.py\nfrom typing import Any, TypeVar, cast\n\nfrom sqlmodel import Field, SQLModel, Table\n\n_T = TypeVar(\"_T\", bound=SQLModel)\n\n\nclass fix_return_type_model(SQLModel):\n    \"\"\"\n    sqlmodel에서 parse_obj 리턴값 정상적으로 수정하기 전까지 사용\n    +\n    validate 또한 같은 문제 있음\n    \"\"\"\n\n    @classmethod\n    def parse_obj(cls: type[_T], obj: Any, update: dict[str, Any] | None = None) -\u003e _T:\n        return cast(_T, super().parse_obj(obj, update))\n\n    @classmethod\n    def validate(cls: type[_T], value: Any) -\u003e _T:\n        return cast(_T, super().validate(value))\n\n\nclass base_model(fix_return_type_model):\n    @classmethod\n    def get_table(cls) -\u003e Table:\n        if (table := getattr(cls, \"__table__\", None)) is None:\n            raise ValueError(\"not table\")\n        return table\n\n\nclass id_model(fix_return_type_model):\n    id: int | None = Field(None, primary_key=True)\n```\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\n@router.post(\n    \"\",\n    response_model=cleaning_public,\n    name=\"cleanings:create-cleaning\",\n    status_code=HTTP_201_CREATED,\n)\nasync def create_new_cleaning(\n    new_cleaning: cleaning_create = Body(..., embed=True),\n    session: AsyncSession = Depends(get_session),\n) -\u003e cleanings:\n    # data = cleanings.from_orm(new_cleaning) 으로 해도 가능\n    # exclude_none=True, exclude_unset=True 옵션을 위해 parse_obj 사용\n    # sqlmodel table=True 관련 validation 문제로 인해 validate사용\n    data = cleanings.validate(\n        new_cleaning.dict(\n            exclude_none=True,\n            exclude_unset=True,\n        )\n    )\n    session.add(data)\n    await session.flush()\n    await session.commit()\n    await session.refresh(data)\n\n    return data\n```\n\n```python\n# backend/tests.py\n(...)\n\n@pytest.fixture\nasync def test_cleaning(engine: AsyncEngine) -\u003e cleanings:\n    new_cleaning_create = cleaning_create.parse_obj(\n        dict(\n            name=\"fake cleaning name\",\n            description=\"fake cleaning description\",\n            price=9.99,\n            cleaning_type=\"spot_clean\",\n        )\n    )\n    new_cleaning = cleanings.validate(new_cleaning_create)\n    async with AsyncSession(engine, autocommit=False) as session:\n        session.add(new_cleaning)\n        await session.commit()\n        await session.refresh(new_cleaning)\n\n    return new_cleaning\n\nclass TestGetCleaning:\n    async def test_get_cleaning_by_id(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(test_cleaning.id))\n        )\n        assert res.status_code == HTTP_200_OK\n        cleaning = cleanings.validate(res.json())\n        assert cleaning == test_cleaning\n\n    @pytest.mark.parametrize(\n        \"id, status_code\",\n        (\n            (500, 404),\n            (-1, 422),\n            (None, 422),\n        ),\n    )\n    async def test_wrong_id_returns_error(\n        self, app: FastAPI, client: AsyncClient, id: int, status_code: int\n    ) -\u003e None:\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(id))\n        )\n        assert res.status_code == status_code\n\n    async def test_get_all_cleanings_returns_valid_response(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        res = await client.get(app.url_path_for(\"cleanings:get-all-cleanings\"))\n        assert res.status_code == HTTP_200_OK\n        assert isinstance((json := res.json()), list)\n        assert len(json) \u003e 0\n        all_cleanings = [cleanings.validate(l) for l in json]\n        assert test_cleaning in all_cleanings\n```\n\n---\n\n## `RESTful` `CRUD` `api` 생성\n\n**RESTful** 표준에 따라, 다음과 같이 엔드포인트를 생성하고자 한다.\n\n| 엔드포인트     | 메소드 | 설명                               |\n| :------------- | :----- | :--------------------------------- |\n| /cleaning      | POST   | 새로운 cleaning 레코드 생성        |\n| /cleaning/{id} | GET    | id에 해당하는 cleaning 레코드 호출 |\n| /cleaning      | GET    | 전체 cleaning 레코드 호출          |\n| /cleaning/{id} | PATCH  | id에 해당하는 cleaning 레코드 수정 |\n| /cleaning/{id} | PUT    | id에 해당하는 cleaning 레코드 교체 |\n| /cleaning/{id} | DELET  | id에 해당하는 cleaning 레코드 제거 |\n\n이전 챕터에서, 새로운 레코드를 생성하는 것과, 기존의 레코드를 `id`를 이용하여 호출하는, 두개의 엔드포인트를 생성했다. 다른 4가지 또한, **TDD** 방법론에 맞게 작성한다.\n\n\u003e 원 예제에서 **jeffastor**는 **PATCH** api를 작성하지 않고 **PUT** api만 작성했다. 그런데 작동 방식을 보면 **jeffastor**가 작성한 **PUT** api는 **PATCH** api처럼 작동한다. 이와 관련해 약간의 수정이 함께 진행된다.\n\n### `GET` `api`\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\n    async def test_get_all_cleanings_returns_valid_response(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        res = await client.get(app.url_path_for(\"cleanings:get-all-cleanings\"))\n        assert res.status_code == HTTP_200_OK\n        assert isinstance((json := res.json()), list)\n        assert len(json) \u003e 0\n        all_cleanings = [cleanings.parse_obj(l) for l in json]    async def test_get_all_cleanings_returns_valid_response(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n        res = await client.get(app.url_path_for(\"cleanings:get-all-cleanings\"))\n        assert res.status_code == HTTP_200_OK\n        assert isinstance((json := res.json()), list)\n        assert len(json) \u003e 0\n        all_cleanings = [cleanings.parse_obj(l) for l in json]\n        assert test_cleaning in all_cleanings\n        assert test_cleaning in all_cleanings\n```\n\n이제 **`pytest`** 를 **`docker`** 컨테이너 내부에서 실행하면, 다음과 같은 에러를 확인할 수 있다.\n\n```bash\n(...)\n\n================================================= FAILURES ==================================================\n_______________________ TestGetCleaning.test_get_all_cleanings_returns_valid_response _______________________\n\nself = \u003ctests.test_cleanings.TestGetCleaning object at 0x7feb2db9b370\u003e\napp = \u003cfastapi.applications.FastAPI object at 0x7feb2b01fd90\u003e\nclient = \u003chttpx.AsyncClient object at 0x7feb2b01e6e0\u003e\ntest_cleaning = cleanings(name='fake cleaning name', price=Decimal('9.99'), id=3, description='fake cleaning description', cleaning_type='spot_clean')\n\n    async def test_get_all_cleanings_returns_valid_response(\n        self, app: FastAPI, client: AsyncClient, test_cleaning: cleanings\n    ) -\u003e None:\n\u003e       res = await client.get(app.url_path_for(\"cleanings:get-all-cleanings\"))\n\ntests/test_cleanings.py:125:\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/usr/local/lib/python3.10/site-packages/starlette/applications.py:108: in url_path_for\n    return self.router.url_path_for(name, **path_params)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = \u003cfastapi.routing.APIRouter object at 0x7feb2b01d180\u003e, name = 'cleanings:get-all-cleanings'\npath_params = {}, route = \u003cfastapi.routing.APIRoute object at 0x7feb2b045480\u003e\n\n    def url_path_for(self, name: str, **path_params: str) -\u003e URLPath:\n        for route in self.routes:\n            try:\n                return route.url_path_for(name, **path_params)\n            except NoMatchFound:\n                pass\n\u003e       raise NoMatchFound()\nE       starlette.routing.NoMatchFound\n\n/usr/local/lib/python3.10/site-packages/starlette/routing.py:590: NoMatchFound\n\n(...)\n```\n\n\u003e 현재 설정으로는, `test_cleaning`을 사용할 때 마다 새로운 레코드를 생성하고 있다. 만약 `unique` 설정이 있다면 에러를 발생시킬 것이다. 이 문제는 이후 다룰 것이므로, 지금은 신경쓰지 않아도 된다고 **jeffastor**는 밝힌다.\n\n이제 테스트를 통과할 수 있도록, 라우터를 수정합니다. 정말 연습해보기 위해, 이후 내용은 제대로 읽지 않고 직접 코드를 작성해봤습니다.\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\nfrom typing import cast\nfrom sqlmodel import select\n\n(...)\n\n@router.get(\n    \"\", response_model=list[cleaning_public], name=\"cleanings:get-all-cleanings\"\n)\nasync def get_all_cleanings(\n    session: AsyncSession = Depends(get_session),\n) -\u003e list[cleanings]:\n    # 아직 sqlmodel의 async session은 type hint와 관련해서 제대로 지원하지 않습니다.\n    # 제대로 작성된게 맞는지 확인해보고 싶다면,\n    # session.sync_session에서 type hint 관련해서만 확인해보면 됩니다.\n    #\n    # sync_session = session.sync_session\n    # table = sync_session.exec(select(cleanings))\n    # rows = table.all()\n    table = await session.exec(select(cleanings))  # type: ignore\n    rows = cast(list[cleanings], table.all())\n    return rows\n\n@router.post(\n    \"\",\n    response_model=cleaning_public,\n    name=\"cleanings:create-cleaning\",\n    status_code=HTTP_201_CREATED,\n)\n\n(...)\n```\n\n테스트 결과 통과했습니다.\n\n\u003e 원 작성자 **jeffator**의 경우, **TDD**에 대해 익숙해지지 위해 처음에는 `None`을 반환하고, 그 다음에는 빈 리스트 `[]`를 반환하고, 그 다음에는 가짜 레코드 `[{ \"id\": 1, \"name\": \"fake cleaning\", \"price\": 0}]`를 반환하고, 끝으로 세션에 연결해서 레코드를 반환합니다.\n\n### `PUT` `api`...? `PATCH` `api`\n\n다음과 같이 테스트 코드를 추가합니다.\n\n```python\n# backend/tests/test_cleanings.py\nfrom contextlib import suppress\nfrom decimal import Decimal, InvalidOperation\n\n(...)\n\nclass TestPutCleaning:\n    @pytest.mark.parametrize(\n        \"attrs_to_change, values\",\n        (\n            ([\"name\"], [\"new fake cleaning name\"]),\n            ([\"description\"], [\"new fake cleaning description\"]),\n            ([\"price\"], [3.14]),\n            ([\"cleaning_type\"], [\"full_clean\"]),\n            (\n                [\"name\", \"description\"],\n                [\n                    \"extra new fake cleaning name\",\n                    \"extra new fake cleaning description\",\n                ],\n            ),\n            ([\"price\", \"cleaning_type\"], [42.00, \"dust_up\"]),\n        ),\n    )\n    async def test_update_cleaning_with_valid_input(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        test_cleaning: cleanings,\n        attrs_to_change: list[str],\n        values: list[str | int | float],\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": dict(zip(attrs_to_change, values))}\n\n        res = await client.put(\n            app.url_path_for(\n                \"cleanings:update-cleaning-by-id-as-put\",\n                id=str(\n                    test_cleaning.id,\n                ),\n            ),\n            json=update_cleaning,\n        )\n        assert res.status_code == HTTP_200_OK\n        updated_cleaning = cleanings.validate(res.json())\n        assert (\n            updated_cleaning.id == test_cleaning.id\n        )  # make sure it's the same cleaning\n        # make sure that any attribute we updated has changed to the correct value\n        for attr, value in zip(attrs_to_change, values):\n            attr_to_change = getattr(updated_cleaning, attr)\n            assert attr_to_change != getattr(test_cleaning, attr)\n            if attr == \"price\":\n                with suppress(InvalidOperation, ValueError):\n                    value = Decimal(f\"{float(value):.2f}\")\n            assert attr_to_change == value\n        # make sure that no other attributes' values have changed\n        for attr, value in updated_cleaning.dict().items():\n            if attr not in attrs_to_change:\n                assert getattr(test_cleaning, attr) == value\n\n    @pytest.mark.parametrize(\n        \"id, payload, status_code\",\n        (\n            (-1, {\"name\": \"test\"}, 422),\n            (0, {\"name\": \"test2\"}, 422),\n            (500, {\"name\": \"test3\"}, 404),\n            (1, None, 422),\n            (1, {\"cleaning_type\": \"invalid cleaning type\"}, 422),\n            (1, {\"cleaning_type\": None}, 400),\n        ),\n    )\n    async def test_update_cleaning_with_invalid_input_throws_error(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        id: int,\n        payload: dict,\n        status_code: int,\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": payload}\n        res = await client.put(\n            app.url_path_for(\"cleanings:update-cleaning-by-id-as-put\", id=str(id)),\n            json=update_cleaning,\n        )\n        assert res.status_code == status_code\n```\n\n첫번째는 **PUT** api가 의도한대로 작동하는지 확인하고, 두번째는 의도한대로 에러를 반환하는지 확인하는 메소드입니다.\n이제 위 테스트 코드를 통과할 수 있도록 **PUT** 메소드를 작성합니다.\n\n\u003e 다만 위 테스트 코드에서 이해가 되지 않는 부분이 있는데,\n\n```python\n# make sure that no other attributes' values have changed\nfor attr, value in updated_cleaning.dict().items():\n    if attr not in attrs_to_change:\n        assert getattr(test_cleaning, attr) == value\n```\n\n\u003e 이다. 이건 **PATCH** 아닌가? 일단 따라가본다.\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\nfrom pydantic import ValidationError\nfrom starlette.status import (\n    HTTP_201_CREATED,\n    HTTP_404_NOT_FOUND,\n    HTTP_422_UNPROCESSABLE_ENTITY,\n)\n\n(...)\n\n@router.put(\n    \"/{id}\",\n    response_model=cleaning_public,\n    name=\"cleanings:update-cleaning-by-id-as-put\",\n)\nasync def update_cleaning_by_id_as_put(\n    id: int = Path(..., ge=1),\n    update_cleaning: cleaning_update = Body(..., embed=True),\n    session: AsyncSession = Depends(get_session),\n) -\u003e cleanings:\n    try:\n        cleanings.from_orm(update_cleaning)\n    except ValidationError as exc:\n        raise HTTPException(\n            status_code=HTTP_422_UNPROCESSABLE_ENTITY, detail=exc.json()\n        )\n\n    if (cleaning := await session.get(cleanings, id)) is None:\n        raise HTTPException(\n            status_code=HTTP_404_NOT_FOUND, detail=\"No cleaning found with that id.\"\n        )\n\n    # validate 관련 문제 해결 전까지는 이렇게..\n    update_dict = update_cleaning.dict(exclude_unset=True)\n    try:\n        cleanings.validate(cleaning.dict() | update_dict)\n    except ValidationError as exc:\n        raise HTTPException(\n            status_code=HTTP_422_UNPROCESSABLE_ENTITY, detail=exc.json()\n        )\n\n    for attr, value in update_dict.items():\n        setattr(cleaning, attr, value)\n            status_code=HTTP_422_UNPROCESSABLE_ENTITY, detail=exc.json()\n        )\n\n    session.add(cleaning)\n    await session.flush()\n    await session.commit()\n    await session.refresh(cleaning)\n\n    return cleaning\n```\n\n`update_cleaning`이 정상적인 `cleanings` 레코드를 생성할 수 있는지 확인하고, `id`에 해당하는 `cleanings` 레코드를 호출 한 다음, 해당 레코드의 값을 수정하고 커밋했다.\n\n테스트 실행결과 이상하다고 생각했던 부분이 맞았다.\n**`pytest`** 에 익숙하지 않아 처음에 알아보지 못한 문제인데,\n\n```python\nattrs_to_change = ['cleaning_type']\nvalues = ['full_clean']\n```\n\n다음과 같이 변수가 정의된다..\n따라서, 위 예제를 모두 **PUT**에서 **PATCH**로 변경 후 다시 진행한다.\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nclass TestPatchCleaning:\n    @pytest.mark.parametrize(\n        \"attrs_to_change, values\",\n        (\n            ([\"name\"], [\"new fake cleaning name\"]),\n            ([\"description\"], [\"new fake cleaning description\"]),\n            ([\"price\"], [3.14]),\n            ([\"cleaning_type\"], [\"full_clean\"]),\n            (\n                [\"name\", \"description\"],\n                [\n                    \"extra new fake cleaning name\",\n                    \"extra new fake cleaning description\",\n                ],\n            ),\n            ([\"price\", \"cleaning_type\"], [42.00, \"dust_up\"]),\n        ),\n    )\n    async def test_update_cleaning_with_valid_input(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        test_cleaning: cleanings,\n        attrs_to_change: list[str],\n        values: list[str | int | float],\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": dict(zip(attrs_to_change, values))}\n\n        res = await client.patch(\n            app.url_path_for(\n                \"cleanings:update-cleaning-by-id-as-patch\",\n                id=str(\n                    test_cleaning.id,\n                ),\n            ),\n            json=update_cleaning,\n        )\n        assert res.status_code == HTTP_200_OK\n        updated_cleaning = cleanings.parse_obj(res.json())\n        assert (\n            updated_cleaning.id == test_cleaning.id\n        )  # make sure it's the same cleaning\n        # make sure that any attribute we updated has changed to the correct value\n        for attr, value in zip(attrs_to_change, values):\n            attr_to_change = getattr(updated_cleaning, attr)\n            assert attr_to_change != getattr(test_cleaning, attr)\n            if attr == \"price\":\n                with suppress(InvalidOperation, ValueError):\n                    value = Decimal(f\"{float(value):.2f}\")\n            assert attr_to_change == value\n        # make sure that no other attributes' values have changed\n        for attr, value in updated_cleaning.dict().items():\n            if attr not in attrs_to_change:\n                assert getattr(test_cleaning, attr) == value\n\n    @pytest.mark.parametrize(\n        \"id, payload, status_code\",\n        (\n            (-1, {\"name\": \"test\"}, 422),\n            (0, {\"name\": \"test2\"}, 422),\n            (500, {\"name\": \"test3\"}, 404),\n            (1, None, 422),\n            (1, {\"cleaning_type\": \"invalid cleaning type\"}, 422),\n            (1, {\"cleaning_type\": None}, 400),\n        ),\n    )\n    async def test_update_cleaning_with_invalid_input_throws_error(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        id: int,\n        payload: dict,\n        status_code: int,\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": payload}\n        res = await client.patch(\n            app.url_path_for(\"cleanings:update-cleaning-by-id-as-patch\", id=str(id)),\n            json=update_cleaning,\n        )\n        assert res.status_code == status_code\n```\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\n@router.patch(\n    \"/{id}\",\n    response_model=cleaning_public,\n    name=\"cleanings:update-cleaning-by-id-as-patch\",\n)\nasync def update_cleaning_by_id_as_patch(\n    id: int = Path(..., ge=1),\n    update_cleaning: cleaning_update = Body(..., embed=True),\n    session: AsyncSession = Depends(get_session),\n) -\u003e cleanings:\n    if (cleaning := await session.get(cleanings, id)) is None:\n        raise HTTPException(\n            status_code=HTTP_404_NOT_FOUND, detail=\"No cleaning found with that id.\"\n        )\n\n    # validate 관련 문제 해결 전까지는 이렇게..\n    update_dict = update_cleaning.dict(exclude_unset=True)\n    try:\n        cleanings.validate(cleaning.dict() | update_dict)\n    except ValidationError as exc:\n        raise HTTPException(\n            status_code=HTTP_422_UNPROCESSABLE_ENTITY, detail=exc.json()\n        )\n\n    for attr, value in update_dict.items():\n        setattr(cleaning, attr, value)\n\n    session.add(cleaning)\n    await session.flush()\n    await session.commit()\n    await session.refresh(cleaning)\n\n    return cleaning\n```\n\n기존에 작성한 **PUT** api는 제거하지 않고 놔둔다. 마지막에 다시 사용할 것이다.\n\n테스트 결과 모두 정상적으로 통과했다.\n\n### `DELETE` `api`\n\n이어서 **DELETE** 테스트 코드와 api를 생성한다.\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nclass TestDeleteCleaning:\n    async def test_can_delete_cleaning_successfully(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        test_cleaning: cleanings,\n    ) -\u003e None:\n        # delete the cleaning\n        res = await client.delete(\n            app.url_path_for(\n                \"cleanings:delete-cleaning-by-id\", id=str(test_cleaning.id)\n            ),\n        )\n        assert res.status_code == HTTP_200_OK\n        # ensure that the cleaning no longer exists\n        res = await client.get(\n            app.url_path_for(\"cleanings:get-cleaning-by-id\", id=str(test_cleaning.id)),\n        )\n        assert res.status_code == HTTP_404_NOT_FOUND\n\n    @pytest.mark.parametrize(\n        \"id, status_code\",\n        (\n            (500, 404),\n            (0, 422),\n            (-1, 422),\n            (None, 422),\n        ),\n    )\n    async def test_delete_cleaning_with_invalid_input_throws_error(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        test_cleaning: cleanings,\n        id: int,\n        status_code: int,\n    ) -\u003e None:\n        res = await client.delete(\n            app.url_path_for(\"cleanings:delete-cleaning-by-id\", id=str(id)),\n        )\n        assert res.status_code == status_code\n```\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\n@router.delete(\"/{id}/\", response_model=int, name=\"cleanings:delete-cleaning-by-id\")\nasync def delete_cleaning_by_id(\n    id: int = Path(..., ge=1, title=\"The ID of the cleaning to delete.\"),\n    session: AsyncSession = Depends(get_session),\n) -\u003e int:\n    if (cleaning := await session.get(cleanings, id)) is None:\n        raise HTTPException(\n            status_code=HTTP_404_NOT_FOUND, detail=\"No cleaning found with that id.\"\n        )\n\n    await session.delete(cleaning)\n    await session.flush()\n    await session.commit()\n\n    return id\n```\n\n테스트도 정상적으로 통과한다.\n\n```bash\ntests/test_cleanings.py::TestDeleteCleaning::test_can_delete_cleaning_successfully PASSED             [ 86%]\ntests/test_cleanings.py::TestDeleteCleaning::test_delete_cleaning_with_invalid_input_throws_error[500-404] PASSED [ 90%]\ntests/test_cleanings.py::TestDeleteCleaning::test_delete_cleaning_with_invalid_input_throws_error[0-422] PASSED [ 93%]\ntests/test_cleanings.py::TestDeleteCleaning::test_delete_cleaning_with_invalid_input_throws_error[-1-422] PASSED [ 96%]\ntests/test_cleanings.py::TestDeleteCleaning::test_delete_cleaning_with_invalid_input_throws_error[None-422] PASSED [100%]\n```\n\n\u003e **DELETE**와 같은 api는 `status_code=204`와 함께 `contents`가 없는 `response`를 반환하는게 맞다고 한다. 현재는 적용하지 않는다.\n\n### `PUT` api\n\n원 예제는 여기서 끝이지만, 추가로 **PUT** api에 대해 직접 작성해본다.\n\n```python\n# backend/tests/test_cleanings.py\n(...)\n\nclass TestPutCleaning:\n    @pytest.mark.parametrize(\n        \"attrs_to_change, values\",\n        (\n            (\n                [\"name\", \"description\", \"price\"],\n                [\n                    \"new fake cleaning name\",\n                    \"new fake cleaning description\",\n                    \"123.1\",\n                ],\n            ),\n            (\n                [\"name\", \"price\", \"cleaning_type\"],\n                [\"extra new fake cleaning name\", 15555.51, \"dust_up\"],\n            ),\n            (\n                [\"name\", \"price\"],\n                [\"extra new fake cleaning name\", Decimal(\"2.12\")],\n            ),\n        ),\n    )\n    async def test_update_cleaning_with_valid_input(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        test_cleaning: cleanings,\n        attrs_to_change: list[str],\n        values: list[str | int | float],\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": dict(zip(attrs_to_change, values))}\n\n        print(orjson.loads(orjson.dumps(update_cleaning, default=str)))\n        res = await client.put(\n            app.url_path_for(\n                \"cleanings:update-cleaning-by-id-as-put\",\n                id=str(test_cleaning.id),\n            ),\n            json=orjson.loads(orjson.dumps(update_cleaning, default=str)),\n        )\n        assert res.status_code == HTTP_200_OK\n        updated_cleaning = cleanings.validate(res.json())\n        assert updated_cleaning.id == test_cleaning.id\n\n        for attr, value in update_cleaning[\"update_cleaning\"].items():\n            if attr == \"price\":\n                with suppress(InvalidOperation, ValueError):\n                    value = Decimal(f\"{float(value):.2f}\")\n            assert value == getattr(updated_cleaning, attr)\n\n        for attr, value in updated_cleaning.dict(exclude={\"id\"}).items():\n            if attr not in attrs_to_change:\n                assert value == cleanings.__fields__[attr].default\n\n    @pytest.mark.parametrize(\n        \"id, payload, status_code\",\n        (\n            (-1, {\"name\": \"test\"}, 422),\n            (0, {\"name\": \"test2\", \"price\": 123}, 422),\n            (500, {\"name\": \"test3\", \"price\": 33.3}, 404),\n            (1, None, 422),\n            (\n                1,\n                {\n                    \"name\": \"test5\",\n                    \"price\": \"123.3\",\n                    \"cleaning_type\": \"invalid cleaning type\",\n                },\n                422,\n            ),\n            (1, {\"name\": \"test6\", \"price\": 123.3, \"cleaning_type\": None}, 422),\n        ),\n    )\n    async def test_update_cleaning_with_invalid_input_throws_error(\n        self,\n        app: FastAPI,\n        client: AsyncClient,\n        id: int,\n        payload: dict,\n        status_code: int,\n    ) -\u003e None:\n        update_cleaning = {\"update_cleaning\": payload}\n        res = await client.patch(\n            app.url_path_for(\"cleanings:update-cleaning-by-id-as-put\", id=str(id)),\n            json=update_cleaning,\n        )\n        assert res.status_code == status_code\n```\n\n```python\n# backend/app/api/routes/cleanings.py\n(...)\n\n@router.put(\n    \"/{id}\",\n    response_model=cleaning_public,\n    name=\"cleanings:update-cleaning-by-id-as-put\",\n)\nasync def update_cleaning_by_id_as_put(\n    id: int = Path(..., ge=1),\n    update_cleaning: cleaning_update = Body(..., embed=True),\n    session: AsyncSession = Depends(get_session),\n) -\u003e cleanings:\n    if (cleaning := await session.get(cleanings, id)) is None:\n        raise HTTPException(\n            status_code=HTTP_404_NOT_FOUND, detail=\"No cleaning found with that id.\"\n        )\n\n    try:\n        new_cleaning = cleanings.validate(update_cleaning.dict(exclude_unset=True))\n    except ValidationError as exc:\n        raise HTTPException(\n            status_code=HTTP_422_UNPROCESSABLE_ENTITY, detail=orjson.loads(exc.json())\n        )\n\n    for attr, value in new_cleaning.dict(exclude={\"id\"}).items():\n        setattr(cleaning, attr, value)\n\n    session.add(cleaning)\n    await session.flush()\n    await session.commit()\n    await session.refresh(cleaning)\n\n    return cleaning\n```\n\n나름 여러 과정을 거쳤는데, **`sqlmodel`** 관련 문제를 알아보다 보니 너무 꼬였다. 과정은 생략..\n\n다음은 마이그레이션 진행 후 유저 관련 설정을 추가하는 것 같다. 유저 관련해서는 **`fastapi-users`** 라는 좋은 라이브러리가 있으니, 원 예제와 같은 흐름이지만 **`fastapi-user`** 를 쓰는 쪽으로 진행할 예정.\n","mtime":"2022-08-13T00:12:20.000+09:00","href":"velog/fastapi 튜토리얼 -5- TDD 방법론으로 RESTful API 생성","data":{"title":"fastapi 튜토리얼 -5- TDD 방법론으로 RESTful API 생성","date":"2022-05-02T20:47:43.741+09:00","tags":["crud","fastapi","restful","tdd","python","@all"],"page":"fastapi 튜토리얼","summary":"fastapi 사용법을 다시 공부할겸, 참고할만한 좋은 예제가 있어서 이 시리즈를 약간의 변경을 주고 따라가보려 한다."}},"page_posts":null},"__N_SSG":true},"page":"/posts/[...name]","query":{"name":["velog","sqlmodel 라이브러리 사용시 주의사항 - validation"]},"buildId":"MQ_lMVQgBI0RkmUA6wvVT","isFallback":false,"gsp":true,"scriptLoader":[]}</script></body></html>